site_name: Everything You Need to Know About Clairify
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features:
    - Primary Email: primary-email.md
    - Email Classification: email-classification.md
    - Summarization: summarization.md
    - Digests: digests.md
    - On-Demand Sync: on-demand-sync.md
    - Channels: channels.md
  - Pricing:
    - feature-matrix.md
  - Security:
    - Security: security.md
    - PII: pii-policy.md
    - OAuth: oauth-scopes.md
  - Latest Release: release-notes/rn-200.md
theme:
  name: material
  features:
    - content.tooltips                 # Style over the browser default tooltip
extra_css:
  - assets/feature-matrix.css
extra_javascript:
  - assets/feature-matrix.js
  - assets/feat-tip.js
plugins:
  - caption:
      table:
        position: top
  - git-revision-date-localized
  - git-latest-changes:
      history_limit: 10                # Number of changes to show
      timestamp_format: "%B %d, %Y, %I:%M %p PST"
      timezone: Etc/GMT+8              # Pacific Standard Time (fixed, no DST)
      table_features:
        - "page_path_link"             # Link to the changed page
        - "timestamp"                  # Show commit timestamp
        - "author"                     # Show commit author
        - "message"                    # Show commit message
markdown_extensions:
  - admonition                         # Render note/warning/info callout blocks
  - attr_list                          # Allow attributes on Markdown elements (e.g., {.class key=value})
  - md_in_html                         # Enable Markdown inside HTML tags (needed for our tables)
  - pymdownx.snippets:                 # Include reusable Markdown/HTML snippets via --8<-- syntax
      base_path: [docs]                # Uses pwd by default. Without this line mkserve fails
      check_paths: true                # Validate that snippet paths exist during build
  - pymdownx.emoji:                    # Render emoji/Material icon shortcodes as inline SVG
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details


 