site_name: Everything You Need to Know About Clairify
nav:
  - Home: index.md
  - Features:
    - Summarization: summarization.md
    - Digests: digests.md
  - Security:
    - Security: security.md
    - OAuth: oauth-scopes.md
theme:
  name: material
plugins:
  - git-revision-date-localized
  - git-latest-changes
markdown_extensions:
  - admonition